// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxhqWF-xbRI38vLk2eJckl3NX3elJ2-w4',
    appId: '1:253443316230:web:7c76d1e39ce3dd928a0187',
    messagingSenderId: '253443316230',
    projectId: 'koalculator-5584c',
    authDomain: 'koalculator-5584c.firebaseapp.com',
    storageBucket: 'koalculator-5584c.appspot.com',
    measurementId: 'G-23BLBEREQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqTheg_J2tptIVdTicdZb2vMkULmEjr0',
    appId: '1:253443316230:android:5cef9c978ed446ee8a0187',
    messagingSenderId: '253443316230',
    projectId: 'koalculator-5584c',
    storageBucket: 'koalculator-5584c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hfUGANDLlJu18jfbMkSrWnX1iYlXnVE',
    appId: '1:253443316230:ios:9b403b8ba1ff4ef78a0187',
    messagingSenderId: '253443316230',
    projectId: 'koalculator-5584c',
    storageBucket: 'koalculator-5584c.appspot.com',
    iosClientId: '253443316230-cugjehi6qfqiuqh07p9hckisclpsmiso.apps.googleusercontent.com',
    iosBundleId: 'com.example.koalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hfUGANDLlJu18jfbMkSrWnX1iYlXnVE',
    appId: '1:253443316230:ios:9b403b8ba1ff4ef78a0187',
    messagingSenderId: '253443316230',
    projectId: 'koalculator-5584c',
    storageBucket: 'koalculator-5584c.appspot.com',
    iosClientId: '253443316230-cugjehi6qfqiuqh07p9hckisclpsmiso.apps.googleusercontent.com',
    iosBundleId: 'com.example.koalculator',
  );
}
